/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Listas;

import MODELO.Jugador;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER-HP
 */
public class FichaJugador extends javax.swing.JInternalFrame {

    DefaultTableModel dfm = new DefaultTableModel();
    DefaultTableModel dfmJuveniles = new DefaultTableModel();
    DefaultTableModel dfmSeniors = new DefaultTableModel();
    
    ArrayList<Jugador> listaJugadores = new ArrayList();
    ArrayList<Jugador> listaJugadoresJuveniles = new ArrayList();
    ArrayList<Jugador> listaJugadoresSeniors = new ArrayList();

    /**
     * Creates new form FichaJugador
     */
    public FichaJugador() {
        initComponents();
        dfm.addColumn("APELLIDOS");
        dfm.addColumn("EDAD");
        dfm.addColumn("PUESTO");
        dfm.addColumn("NACIONALIDAD");
        dfm.addColumn("GOLES");
        tblDatos.setModel(dfm);

    }

    public String[] datos(String datos) {
        String[] informacion = new String[4];

        if (datos.equalsIgnoreCase("portero")) {
            informacion[0] = "-";
        }
        if (datos.equalsIgnoreCase("defensa")) {
            informacion[0] = "central";
            informacion[1] = "lateral";
            informacion[2] = "libre";
            informacion[3] = "carrilero";
        }
        if (datos.equalsIgnoreCase("centrocampista")) {
            informacion[0] = "pivote";
            informacion[1] = "media punta";
            informacion[2] = "volante";
            informacion[3] = "interior";
        }
        if (datos.equalsIgnoreCase("delantero")) {
            informacion[0] = "segundo delantero";
            informacion[1] = "delantero centro";
            informacion[2] = "extremo";
        }
        return informacion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbPuesto = new javax.swing.JComboBox<>();
        cmbOpcion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtGoles = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cmbOpcionListas = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblGoleadorJuvenil = new javax.swing.JLabel();
        lblGoleadorSenior = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("JUGADOR");

        jLabel1.setText("DATOS DEL JUGADOR");

        jLabel2.setText("apellidos");

        jLabel3.setText("edad");

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        jLabel4.setText("puesto");

        cmbPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-SELECCIONAR-", "portero", "defensa", "centrocampista", "delantero" }));
        cmbPuesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPuestoItemStateChanged(evt);
            }
        });
        cmbPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPuestoActionPerformed(evt);
            }
        });

        cmbOpcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jLabel5.setText("nacionalidad");

        jLabel6.setText("goles");

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnLimpiar.setText("limpiarTabla");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        cmbOpcionListas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "juveniles", "seniors" }));

        jLabel7.setText("LISTAS ");

        btnFiltrar.setText("filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        jLabel8.setText("Maximo goleador juvenil:");

        jLabel9.setText("Maximo goleador senior:");

        lblGoleadorJuvenil.setText("jLabel10");

        lblGoleadorSenior.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(txtGoles, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(143, 143, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1)
                        .addGap(64, 64, 64)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(46, 46, 46)
                                .addComponent(cmbOpcionListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnFiltrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblGoleadorSenior)
                                    .addComponent(lblGoleadorJuvenil))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOpcionListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(btnFiltrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblGoleadorJuvenil))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblGoleadorSenior))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPuestoActionPerformed

    }//GEN-LAST:event_cmbPuestoActionPerformed

    private void cmbPuestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPuestoItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (this.cmbPuesto.getSelectedIndex() > 0) {
                this.cmbOpcion.setModel(new DefaultComboBoxModel(this.datos(this.cmbPuesto.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_cmbPuestoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String puesto = cmbOpcion.getSelectedItem().toString();
        String opcion = cmbOpcion.getSelectedItem().toString();

        Jugador jugador = new Jugador(txtApellidos.getText(), txtEdad.getText(), puesto + opcion, txtNacionalidad.getText(), txtGoles.getText());

        listaJugadores.add(jugador);

        dfm.addRow(new Object[]{
            jugador.getApellido(), jugador.getEdad(), jugador.getPuesto(), jugador.getNacionalidad(), jugador.getGoles()
        });

        if (Integer.parseInt(jugador.getEdad()) < 23) {
            listaJugadoresJuveniles.add(jugador);

        } else if (Integer.parseInt(jugador.getEdad()) >= 23) {
            listaJugadoresSeniors.add(jugador);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarTabla();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed

        String opcionLista = cmbOpcionListas.getSelectedItem().toString();

        System.out.println(opcionLista);

        if (opcionLista.equals("juveniles")) {
            imprimirJuveniles();
            goleadorJuvenil();

        } else if (opcionLista.equalsIgnoreCase("seniors")) {
            imprimirSeniors();
            goleadorSenior();
        }
    }//GEN-LAST:event_btnFiltrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbOpcion;
    private javax.swing.JComboBox<String> cmbOpcionListas;
    private javax.swing.JComboBox<String> cmbPuesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGoleadorJuvenil;
    private javax.swing.JLabel lblGoleadorSenior;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGoles;
    private javax.swing.JTextField txtNacionalidad;
    // End of variables declaration//GEN-END:variables

    private void limpiarTabla() {
        int filas = dfm.getRowCount();
        for (int i = 0; i < filas; i++) {
            dfm.removeRow(0);

        }
    }

    private void imprimirJuveniles() {
        limpiarTabla();

        for (Jugador jugador : listaJugadoresJuveniles) {

            dfm.addRow(new Object[]{
                jugador.getApellido(), jugador.getEdad(), jugador.getPuesto(), jugador.getNacionalidad(), jugador.getGoles()
            });

        }
    }

    private void imprimirSeniors() {
        limpiarTabla();

        for (Jugador jugador : listaJugadoresSeniors) {

            dfm.addRow(new Object[]{
                jugador.getApellido(), jugador.getEdad(), jugador.getPuesto(), jugador.getNacionalidad(), jugador.getGoles()
            });
        }
    }

    private void goleadorJuvenil() {
        Jugador jugadorMayorGoles = null;

        for (Jugador jugador : listaJugadoresJuveniles) {
            if (jugadorMayorGoles == null || Integer.parseInt(jugador.getGoles()) > Integer.parseInt(jugadorMayorGoles.getGoles())) {
                jugadorMayorGoles = jugador;
            }

        }

        String goleador1 = jugadorMayorGoles.getApellido() + jugadorMayorGoles.getGoles();

        lblGoleadorJuvenil.setText("Nombre: " + goleador1 + "Nro de goles" + jugadorMayorGoles.getGoles());
    }

    private void goleadorSenior() {
        Jugador jugadorMayorGoles = null;
        for (Jugador jugador : listaJugadoresSeniors) {
            if (jugadorMayorGoles == null || Integer.parseInt(jugador.getGoles()) > Integer.parseInt(jugadorMayorGoles.getGoles())) {
                jugadorMayorGoles = jugador;
            }

        }
        System.out.println("goleador senior" + jugadorMayorGoles.getApellido() + jugadorMayorGoles.getGoles());
        String goleador1 = jugadorMayorGoles.getApellido() + jugadorMayorGoles.getGoles();

        lblGoleadorSenior.setText("Nombre: " + goleador1 + "Nro de goles" + jugadorMayorGoles.getGoles());
    }
}
