package Colas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */


import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class EJEM_7 extends javax.swing.JInternalFrame {

    /**
     * Creates new form EJEM_7
     */
    public EJEM_7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnsumar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtnumeros = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnumeros2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnagregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtresul = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        btnsumar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnsumar.setText("SUMAR");
        btnsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("SUMAR COLAS");

        txtnumeros.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("INGRESAR COLA 1 :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("SUMATORIA DE LA COLA :");

        txtnumeros2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("INGRESAR COLA 2 :");

        btnagregar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        txtresul.setColumns(20);
        txtresul.setRows(5);
        jScrollPane1.setViewportView(txtresul);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtnumeros2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnagregar)
                        .addGap(81, 81, 81)
                        .addComponent(btnsumar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnumeros2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar)
                    .addComponent(btnsumar))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   Queue<Integer> colan1 = new LinkedList<>();
      Queue<Integer> colan2 = new LinkedList<>();
      Queue<Integer> resultadoCola = new LinkedList<>();
    private void btnsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumarActionPerformed
        resultadoCola = sumarColas(colan1, colan2);

    int sumatoria = 0;
    StringBuilder resultado = new StringBuilder(" ");

    for (int elemento : resultadoCola) {
        sumatoria += elemento;
        resultado.append(elemento).append(" + ");
    }

    if (!resultadoCola.isEmpty()) {
        resultado.setLength(resultado.length() - 3); // Elimina el último " + "
    }

    resultado.append(" = ").append(sumatoria);

    // Muestra el resultado en tu interfaz gráfica, por ejemplo, en un componente de texto como txtresul
    txtresul.setText(resultado.toString());

    }//GEN-LAST:event_btnsumarActionPerformed
 

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        // TODO add your handling code here:
           String inputCola1 = txtnumeros.getText();
        String inputCola2 = txtnumeros2.getText();

        llenarCola(inputCola1, colan1);
        llenarCola(inputCola2, colan2);

        // Puedes realizar acciones adicionales aquí, como mostrar el contenido de las colas en la interfaz gráfica.
        
        txtnumeros.setText("");
        txtnumeros2.setText("");
    }//GEN-LAST:event_btnagregarActionPerformed
   private void llenarCola(String input, Queue<Integer> cola) {
        String[] valores = input.split(",");

        for (String valor : valores) {
            if (!valor.trim().equals("")) {
                try {
                    int elemento = Integer.parseInt(valor.trim());
                    cola.offer(elemento);
                } catch (NumberFormatException e) {
                    // Manejar la excepción si no es un número válido
                }
            }
        }
    }

    private Queue<Integer> sumarColas(Queue<Integer> cola1, Queue<Integer> cola2) {
        Queue<Integer> resultado = new LinkedList<>();

        while (!cola1.isEmpty() && !cola2.isEmpty()) {
            int elemento1 = cola1.poll();
            int elemento2 = cola2.poll();
            resultado.offer(elemento1 + elemento2);
        }

        // Puedes manejar las colas restantes si tienen tamaños diferentes aquí
        while (!cola1.isEmpty()) {
            resultado.offer(cola1.poll());
        }

        while (!cola2.isEmpty()) {
            resultado.offer(cola2.poll());
        }

        return resultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnsumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtnumeros;
    private javax.swing.JTextField txtnumeros2;
    private javax.swing.JTextArea txtresul;
    // End of variables declaration//GEN-END:variables
}
