/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Queue;
import javax.management.Query;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oli
 */
public class CEjercicio2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form CEjercicio2
     */
    public CEjercicio2() {
        initComponents();
        setModelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxEstado = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSolicitudes = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAtencion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbxComplemento = new javax.swing.JComboBox<>();
        btnSolicitar = new javax.swing.JButton();
        txtCancelacion = new javax.swing.JTextField();
        btnAtender = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        cbxEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Llegada", "Atención" }));

        tblSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Solicitudes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSolicitudes);

        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Consultas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblConsultas);

        tblAtencion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Atención"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblAtencion);

        jLabel1.setText("Seleccione el tipo de servicio:");

        cbxComplemento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxComplemento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Consulta", "Cancelación", "Solicitud" }));

        btnSolicitar.setText("Solicitar");
        btnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarActionPerformed(evt);
            }
        });

        txtCancelacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnAtender.setText("Atender");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });

        jLabel2.setText("Numero de consulta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSolicitar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtender))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                        .addComponent(txtCancelacion, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbxComplemento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxEstado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(cbxComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCancelacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSolicitar)
                            .addComponent(btnAtender))))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int numAtencion = 0;

    Queue<Integer> colaSolicitudes = new LinkedList<>();
    Queue<Integer> colaConsultas = new LinkedList<>();
    Queue<Integer> atendidos =new LinkedList<>();
    DefaultTableModel modeloSolicitudes=new DefaultTableModel();
    DefaultTableModel modeloConsultas=new DefaultTableModel();
    DefaultTableModel modeloAtencion=new DefaultTableModel();

    private static void eliminarValor(Queue<Integer> cola, int valor) {
        Queue<Integer> colaAuxiliar = new LinkedList<>();
        while (!cola.isEmpty()) {
            int elemento = cola.poll();
            if (elemento != valor) {
                colaAuxiliar.offer(elemento);
            }
        }
        cola.addAll(colaAuxiliar);
    }
    
    private void btnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarActionPerformed
        if (cbxEstado.getSelectedItem().toString().equals("Llegada")) {
            if (cbxComplemento.getSelectedItem().toString().equals("Consulta")) {
                numAtencion++;
                colaConsultas.add(numAtencion);
                setFila(modeloConsultas, colaConsultas);
            } else if (cbxComplemento.getSelectedItem().toString().equals("Solicitud")) {
                numAtencion++;
                colaSolicitudes.add(numAtencion);
                setFila(modeloSolicitudes, colaSolicitudes);
            } else {
                int numCancelacion=Integer.parseInt(txtCancelacion.getText());
                if(colaConsultas.contains(numCancelacion)){
                    eliminarValor(colaConsultas, numCancelacion);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se encontrón su consulta");
                }
                setFila(modeloConsultas, colaConsultas);
            }
        }
    }//GEN-LAST:event_btnSolicitarActionPerformed

    public void setModelo(){
        String[] cabecera={"Solicitudes"};
        String[] cabecera2={"Consultas"};
        String[] cabecera3={"Atención"};
        modeloSolicitudes.setColumnIdentifiers(cabecera);
        modeloConsultas.setColumnIdentifiers(cabecera2);
        modeloAtencion.setColumnIdentifiers(cabecera3);
        tblConsultas.setModel(modeloConsultas);
        tblSolicitudes.setModel(modeloSolicitudes);
        tblAtencion.setModel(modeloAtencion);
    }
    
    public void setFila(DefaultTableModel modelo,Queue<Integer> cola){
        modelo.setRowCount(0);
        for (Integer numero : cola) {
            modelo.addRow(new Object[]{numero});
        }
    }
    
    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        if(cbxEstado.getSelectedItem().toString().equals("Atención")){
            if(cbxComplemento.getSelectedItem().toString().equals("Consulta")){
                atendidos.add(colaConsultas.remove());
                setFila(modeloConsultas, colaConsultas);
                setFila(modeloAtencion, atendidos);
            }else if(cbxComplemento.getSelectedItem().toString().equals("Solicitud")){
                atendidos.add(colaSolicitudes.remove());
                setFila(modeloSolicitudes, colaSolicitudes);
                setFila(modeloAtencion, atendidos);
            }else{
                int numCancelacion=Integer.parseInt(txtCancelacion.getText());
                if(colaConsultas.contains(numCancelacion)){
                    eliminarValor(colaConsultas, numCancelacion);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se encontrón su conulta");
                }
                setFila(modeloConsultas, colaConsultas);
            }
            
        }
    }//GEN-LAST:event_btnAtenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnSolicitar;
    private javax.swing.JComboBox<String> cbxComplemento;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblAtencion;
    private javax.swing.JTable tblConsultas;
    private javax.swing.JTable tblSolicitudes;
    private javax.swing.JTextField txtCancelacion;
    // End of variables declaration//GEN-END:variables
}
