/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU;

import MODELO.Jugador;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sarita
 */
public class Datos_Jugador extends javax.swing.JInternalFrame {
    ArrayList<Jugador> listaJugador=new ArrayList<>();
    DefaultTableModel modelo;
     DefaultTableModel modeloJovenes;
    DefaultTableModel modeloMayores;
    int golesGoleadorJovenes = 0;
    int golesGoleadorMayores = 0;
    String nombreGoleadorJovenes = "";
    String nombreGoleadorMayores = "";
    /**
     * Creates new form Datos_Jugador
     */
    public Datos_Jugador() {
        initComponents();
    }
    public String[]datos(String datos){
        String[]informacion=new String[5];
        if(datos.equalsIgnoreCase("Portero")){
         informacion[0]="portero";
        }
        if(datos.equalsIgnoreCase("Defensa")){
         informacion[0]="Defensa central";
         informacion[1]="Lateral";
         informacion[2]="Libre";
         informacion[3]="Carrillero";
        }
        if(datos.equalsIgnoreCase("Controcampista")){
         informacion[0]="Media punta";
         informacion[1]="volante";
         informacion[2]="interior";
        }
        if(datos.equalsIgnoreCase("Delantero")){
         informacion[0]="Segundo delantero";
         informacion[1]="Delantero centro";
         informacion[2]="extremo";
        }
        return informacion;
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGol = new javax.swing.JTextField();
        txtNacion = new javax.swing.JTextField();
        Combo1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        Combo2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbJovenes = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblGol1 = new javax.swing.JLabel();
        lblGol2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbMayores = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("DATOS DE JUGADOR_ ARRAY LIST");

        jLabel1.setText("APELLIDOS:");

        jLabel2.setText("EDAD:");

        jLabel3.setText("NACIONALIDAD:");

        jLabel4.setText("GOLES:");

        Combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Portero", "Defensa", "Centrocampista", "Delantero" }));
        Combo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Combo1ItemStateChanged(evt);
            }
        });
        Combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo1ActionPerformed(evt);
            }
        });

        jLabel5.setText("PUESTO:");

        jLabel6.setText("Elija Habilidad-->");

        btnReg.setText("VER REGISTRO");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        tbJovenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JOVENES MENOR DE 23"
            }
        ));
        jScrollPane2.setViewportView(tbJovenes);

        jLabel7.setText("EJERCICIO 4");

        jLabel8.setText("GOLEADOR MENOR DE 23:");

        jLabel9.setText("GOLEADOR MAYOR DE 23:");

        lblGol1.setText("-----");

        lblGol2.setText("-----");

        tbMayores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SEÑORES MAYORES DE 23"
            }
        ));
        jScrollPane3.setViewportView(tbMayores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel7)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblGol2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblGol1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txtNacion, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4)))
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGol, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReg)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReg)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblGol1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblGol2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo1ActionPerformed
     private void actualizarTabla() {
        // Limpiar la tabla
        DefaultTableModel modeloJovenes = (DefaultTableModel) tbJovenes.getModel();
        DefaultTableModel modeloMayores = (DefaultTableModel) tbMayores.getModel();
        modeloJovenes.setRowCount(0);
        modeloMayores.setRowCount(0);

        for (Jugador jugador : listaJugador) {
            if (jugador.getEdad() < 23) {
                modeloJovenes.addRow(new Object[] { jugador.getApellido(), jugador.getEdad(), jugador.getPuesto(), jugador.getNacionalidad(), jugador.getGoles() });
            } else {
                modeloMayores.addRow(new Object[] { jugador.getApellido(), jugador.getEdad(), jugador.getPuesto(), jugador.getNacionalidad(), jugador.getGoles() });
            }
           
        if (jugador.getEdad() < 23) {
            if (jugador.getGoles() > golesGoleadorJovenes) {
                golesGoleadorJovenes = jugador.getGoles();
                nombreGoleadorJovenes = jugador.getApellido();
                lblGol1.setText("Goleador Joven: " + nombreGoleadorJovenes + " - Goles: " + golesGoleadorJovenes);
            }
        } else {
            if (jugador.getGoles() > golesGoleadorMayores) {
                golesGoleadorMayores = jugador.getGoles();
                nombreGoleadorMayores = jugador.getApellido();
                lblGol2.setText("Goleador Mayor: " + nombreGoleadorMayores + " - Goles: " + golesGoleadorMayores);
            }
        }
        }
        
    }
    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
        try {
         String apellido = txtApellido.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String nacion = txtNacion.getText();
            int gol = Integer.parseInt(txtGol.getText());
            String puesto = Combo2.getSelectedItem().toString();
            
            Jugador jugador = new Jugador(apellido, edad, puesto, nacion, gol);
            listaJugador.add(jugador);
            
            
            actualizarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al ingresar los datos");
        }
        
    }//GEN-LAST:event_btnRegActionPerformed

    private void Combo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Combo1ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            if(Combo1.getSelectedIndex() > 0){
                Combo2.setModel(new DefaultComboBoxModel(datos(Combo1.getSelectedItem().toString())));
            }
        }
    }//GEN-LAST:event_Combo1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Combo1;
    private javax.swing.JComboBox<String> Combo2;
    private javax.swing.JButton btnReg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGol1;
    private javax.swing.JLabel lblGol2;
    private javax.swing.JTable tbJovenes;
    private javax.swing.JTable tbMayores;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGol;
    private javax.swing.JTextField txtNacion;
    // End of variables declaration//GEN-END:variables
}
