/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class FiltrarJugadores extends javax.swing.JInternalFrame {

    /**
     * Creates new form FiltrarJugadores
     */
    public String apellidos, edad, puesto, posicion, nacionalidad, goles, categoria;
    ArrayList<Jugador> listaJugadores = new ArrayList<>();
    DefaultTableModel modelo1 = new DefaultTableModel();

    public void setListaJugadores(ArrayList<Jugador> listaJugadores) {
        this.listaJugadores = listaJugadores;
    }

    public FiltrarJugadores() {
        initComponents();
        setModelo1();
    }

    public void setModelo1() {
        String[] cabecera = {"Nro.", "Apellidos", "Edad", "Puesto", "Posicion", "Nacionalidad", "Goles", "Categoria"};
        modelo1.setColumnIdentifiers(cabecera);
        tblJugadores.setModel(modelo1);
    }

    public void llenarTabla1() {

        Jugador juvenil = new Jugador(apellidos,
                edad != null ? Integer.parseInt(edad) : 0,
                puesto, posicion, nacionalidad,
                goles != null ? Integer.parseInt(goles) : 0,
                categoria);
        listaJugadores.add(juvenil);
    }

    private void setDatos1() {
        // ESTRUCTUTA INFORMACIÓN TABLA
        Object[] filas = new Object[modelo1.getColumnCount()];
        int contador = 1;
        for (Jugador puntero : listaJugadores) {
            filas[0] = contador;
            filas[1] = puntero.getApellidos();
            filas[2] = puntero.getEdad();
            filas[3] = puntero.getPuesto();
            filas[4] = puntero.getPosicion();
            filas[5] = puntero.getNacionalidad();
            filas[6] = puntero.getGoles();
            filas[7] = puntero.getCategoria();

            modelo1.addRow(filas);

            contador++;

        }
        tblJugadores.setModel(modelo1);

    }

    Jugador maxGoleadorJuvenil = null;
    Jugador maxGoleadorSenior = null;

    private void encontrarMaximosGoleadores() {
        for (Jugador jugador : listaJugadores) {
            String categoria = jugador.getCategoria();
            if (categoria != null) {
                if (categoria.equals("Juvenil")) {
                    if (maxGoleadorJuvenil == null || jugador.getGoles() > maxGoleadorJuvenil.getGoles()) {
                        maxGoleadorJuvenil = jugador;
                    }
                } else if (categoria.equals("Senior")) {
                    if (maxGoleadorSenior == null || jugador.getGoles() > maxGoleadorSenior.getGoles()) {
                        maxGoleadorSenior = jugador;
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJugadores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblMaximosGoleadores = new javax.swing.JTable();
        lblGoleadores = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TABLA DE JUGADORES FILTRADOS");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lblTitulo.setText("Listado de jugadores juveniles ");

        tblJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblJugadores);

        lblMaximosGoleadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(lblMaximosGoleadores);

        lblGoleadores.setText("Maximos goleadores de cada equipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblGoleadores)
                .addGap(405, 405, 405))
            .addGroup(layout.createSequentialGroup()
                .addGap(412, 412, 412)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTitulo)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblGoleadores)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        llenarTabla1();
        setDatos1();
        encontrarMaximosGoleadores();
        mostrarMaximosGoleadoresEnTabla();
    }//GEN-LAST:event_formInternalFrameActivated
    private void mostrarMaximosGoleadoresEnTabla() {
        // ESTRUCTUTA INFORMACIÓN TABLA
        DefaultTableModel modeloMaximosGoleadores = new DefaultTableModel();
        String[] cabecera = {"Categoria", "Nro.", "Apellidos", "Edad", "Puesto", "Posicion", "Nacionalidad", "Goles"};
        modeloMaximosGoleadores.setColumnIdentifiers(cabecera);
        lblMaximosGoleadores.setModel(modeloMaximosGoleadores);

        if (maxGoleadorJuvenil != null) {
            Object[] filaJuvenil = {"Juvenil", 1, maxGoleadorJuvenil.getApellidos(), maxGoleadorJuvenil.getEdad(),
                maxGoleadorJuvenil.getPuesto(), maxGoleadorJuvenil.getPosicion(), maxGoleadorJuvenil.getNacionalidad(),
                maxGoleadorJuvenil.getGoles()};
            modeloMaximosGoleadores.addRow(filaJuvenil);
        }

        if (maxGoleadorSenior != null) {
            Object[] filaSenior = {"Senior", 1, maxGoleadorSenior.getApellidos(), maxGoleadorSenior.getEdad(),
                maxGoleadorSenior.getPuesto(), maxGoleadorSenior.getPosicion(), maxGoleadorSenior.getNacionalidad(),
                maxGoleadorSenior.getGoles()};
            modeloMaximosGoleadores.addRow(filaSenior);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblGoleadores;
    private javax.swing.JTable lblMaximosGoleadores;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblJugadores;
    // End of variables declaration//GEN-END:variables
}
