/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU;

import DIU.Modelo.Persona;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class ListasDinamicas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListasDinamicas
     */
    public ListasDinamicas() {
        initComponents();
        Tablamodelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtingresar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtabla = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("INGRESAR NOMBRES :");

        txtingresar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtingresarMouseClicked(evt);
            }
        });
        txtingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingresarActionPerformed(evt);
            }
        });

        txtabla.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "NOMBRES"
            }
        ));
        jScrollPane2.setViewportView(txtabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(txtingresar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtingresar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtingresarActionPerformed
    ArrayList<Persona> listanombre=new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();
    public void Tablamodelo(){
        String[] cabecera={"N°","Nombres"};
        modelo.setColumnIdentifiers(cabecera);
        txtabla.setModel(modelo);
    }
    public void llenarArray(){
        String nombre = txtingresar.getText();
        Persona persona=new Persona(nombre);
        listanombre.add(persona);
        
    }
    public void Datos(){
        Object[]informacion=new Object[modelo.getColumnCount()];
        int Cont=1;
        modelo.setRowCount(0);
        for (Persona ListaNom : listanombre) {
            informacion[0]=Cont;
            informacion[1]=ListaNom.getNombre();
            Cont++;
            modelo.addRow(informacion);
        }
        txtabla.setModel(modelo);
    }
    private void txtingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtingresarMouseClicked
        // TODO add your handling code here:
        //instancia del objeto persona 
      llenarArray();
       Datos();
//    Persona p = new Persona(nombre);
//    listanombre.add(p);
//    txtingresar.setText("");
//    for (Persona persona : listanombre) {
//        txtarea.append(persona.getNombre() + "\n");
//    }

    }//GEN-LAST:event_txtingresarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable txtabla;
    private javax.swing.JTextField txtingresar;
    // End of variables declaration//GEN-END:variables
}
