/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU;

import DIU.modelo.Numeros1;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class ListasEstaticas1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListasEstaticas1
     */
    public String numero;
    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelo2 = new DefaultTableModel();
    ArrayList<Numeros1> listaNumeros = new ArrayList<>();

    public ListasEstaticas1() {
        initComponents();
        setModelo();
    }

    public void setModelo() {
        String[] cabecera = {"Valor 1", "Valor 2", "Valor 3", "Valor 4", "Valor 5",
            "Valor 6", "Valor 7", "Valor 8", "Valor 9", "Valor 10"};
        modelo.setColumnIdentifiers(cabecera);
        tblNumeros1.setModel(modelo);

    }

    public void llenarTabla() {
        String numero = txtNumeros.getText();

        if (listaNumeros.size() < 10) {
            Numeros1 numeros = new Numeros1(Integer.parseInt(numero));
            listaNumeros.add(numeros);

            txtNumeros.setText("");
        } else {
            // Mostrar un mensaje de error si se intenta ingresar más de 10 números
            JOptionPane.showMessageDialog(rootPane, "Ya has ingresado 10 números. No se pueden ingresar más.");
        }
    }

    public void setDatos() {
        // ESTRUCTURA DE INFORMACIÓN PARA tblNumeros1
        Object[] lista = new Object[modelo.getColumnCount()];

        for (int i = 0; i < 10; i++) {
            lista[i] = listaNumeros.get(i).getNumero();
        }

        modelo.addRow(lista);
        tblNumeros1.setModel(modelo);

        // Invertir la lista de números antes de agregarla a tblNumeros2
        Collections.reverse(listaNumeros);

        // Obtener los nombres de las columnas del modelo original
        Vector<String> nombresColumnas = new Vector<>();
        for (int i = 0; i < modelo.getColumnCount(); i++) {
            nombresColumnas.add(modelo.getColumnName(i));
        }

        // Configurar los nombres de las columnas en modelo2
        modelo2.setColumnIdentifiers(nombresColumnas);
        modelo2.addRow(listaNumeros.stream().map(Numeros1::getNumero).toArray());
        tblNumeros2.setModel(modelo2);
    }

    private void encontrarMayorMenor() {
        // Verificar si hay al menos un número en la lista
        if (listaNumeros.size() > 0) {
            // Encontrar el número mayor y menor
            int mayor = listaNumeros.get(0).getNumero();
            int menor = listaNumeros.get(0).getNumero();

            for (int i = 0; i < listaNumeros.size(); i++) {
                // Suponiendo que la clase Numeros1 tiene un método getNumero()
                int numeroActual = listaNumeros.get(i).getNumero();

                if (numeroActual > mayor) {
                    mayor = numeroActual;
                }

                if (numeroActual < menor) {
                    menor = numeroActual;
                }
            }

            // Mostrar los resultados en las etiquetas
            lblResultadoMayor.setText(String.valueOf(mayor));
            lblResultadoMenor.setText(String.valueOf(menor));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblNumeros = new javax.swing.JLabel();
        lblMayor = new javax.swing.JLabel();
        lblMenor = new javax.swing.JLabel();
        lblResultadoMayor = new javax.swing.JLabel();
        lblResultadoMenor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNumeros1 = new javax.swing.JTable();
        txtNumeros = new javax.swing.JTextField();
        btnGenerarLista = new javax.swing.JButton();
        lblLista1 = new javax.swing.JLabel();
        lblLista2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNumeros2 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("LISTAS ESTATICAS EJERCICIO 1");

        lblTitulo.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 204, 102));
        lblTitulo.setText("Listas Estáticas");

        lblNumeros.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeros.setText("Ingrese 10 números enteros por separado:");

        lblMayor.setForeground(new java.awt.Color(0, 0, 0));
        lblMayor.setText("Número mayor:");

        lblMenor.setForeground(new java.awt.Color(0, 0, 0));
        lblMenor.setText("Número menor:");

        tblNumeros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNumeros1);

        txtNumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerosActionPerformed(evt);
            }
        });

        btnGenerarLista.setText("Generar");
        btnGenerarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarListaActionPerformed(evt);
            }
        });

        lblLista1.setText("Lista 1:");

        lblLista2.setText("Lista 2:");

        tblNumeros2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblNumeros2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeros)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGenerarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNumeros))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMayor)
                    .addComponent(lblMenor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResultadoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResultadoMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblLista2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblLista1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNumeros)
                        .addComponent(txtNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblResultadoMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMenor)
                            .addComponent(lblResultadoMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerarLista)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblLista1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLista2)
                        .addGap(70, 70, 70))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarListaActionPerformed
        // TODO add your handling code here:
        encontrarMayorMenor();
        setDatos();
    }//GEN-LAST:event_btnGenerarListaActionPerformed

    private void txtNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerosActionPerformed
        this.llenarTabla();
    }//GEN-LAST:event_txtNumerosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLista1;
    private javax.swing.JLabel lblLista2;
    private javax.swing.JLabel lblMayor;
    private javax.swing.JLabel lblMenor;
    private javax.swing.JLabel lblNumeros;
    private javax.swing.JLabel lblResultadoMayor;
    private javax.swing.JLabel lblResultadoMenor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblNumeros1;
    private javax.swing.JTable tblNumeros2;
    private javax.swing.JTextField txtNumeros;
    // End of variables declaration//GEN-END:variables
}
