/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DIU;

import DiuVistas.personaView;
import EjercicioColecciones.Ejercicio1;
import EjercicioColecciones.Ejercicio2;
import EjercicioColecciones.Ejercicio3;
import EjercicioColecciones.Ejercicio4;
import EjercicioColecciones.Ejercicio5;
import EjercicioColecciones.Ejercicio6;
import EjercicioColecciones.Ejercicio7;
import Listas.ListasEstaticas;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        opLEstaticas = new javax.swing.JMenu();
        opLEstatico = new javax.swing.JMenuItem();
        opLDinamicas = new javax.swing.JMenuItem();
        OpListasEstaticas2 = new javax.swing.JMenuItem();
        Ejercicio1 = new javax.swing.JMenuItem();
        Ejercicio2 = new javax.swing.JMenuItem();
        Ejercicio3 = new javax.swing.JMenuItem();
        Ejercicio4 = new javax.swing.JMenuItem();
        menuPilas = new javax.swing.JMenu();
        Ejercicio5 = new javax.swing.JMenuItem();
        Ejercicio6 = new javax.swing.JMenuItem();
        menuArboles = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        Ejercicio7 = new javax.swing.JMenuItem();
        Ejercicio8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuFicha = new javax.swing.JMenuItem();
        ReportePagarT = new javax.swing.JMenuItem();
        Gestion = new javax.swing.JMenu();
        GestionUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1387, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        opLEstaticas.setText("Listas");

        opLEstatico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        opLEstatico.setText("Estáticas");
        opLEstatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLEstaticoActionPerformed(evt);
            }
        });
        opLEstaticas.add(opLEstatico);

        opLDinamicas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        opLDinamicas.setText("Dinámicas");
        opLEstaticas.add(opLDinamicas);

        OpListasEstaticas2.setText("ListasEstaticas2");
        OpListasEstaticas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpListasEstaticas2ActionPerformed(evt);
            }
        });
        opLEstaticas.add(OpListasEstaticas2);

        Ejercicio1.setText("Ejercicio1");
        Ejercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio1ActionPerformed(evt);
            }
        });
        opLEstaticas.add(Ejercicio1);

        Ejercicio2.setText("Ejercicio2");
        Ejercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio2ActionPerformed(evt);
            }
        });
        opLEstaticas.add(Ejercicio2);

        Ejercicio3.setText("Ejercicio3");
        Ejercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio3ActionPerformed(evt);
            }
        });
        opLEstaticas.add(Ejercicio3);

        Ejercicio4.setText("Ejercicio4");
        Ejercicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio4ActionPerformed(evt);
            }
        });
        opLEstaticas.add(Ejercicio4);

        jMenuBar1.add(opLEstaticas);

        menuPilas.setText("Pilas");

        Ejercicio5.setText("Ejercicio5");
        Ejercicio5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio5ActionPerformed(evt);
            }
        });
        menuPilas.add(Ejercicio5);

        Ejercicio6.setText("Ejercicio6");
        Ejercicio6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio6ActionPerformed(evt);
            }
        });
        menuPilas.add(Ejercicio6);

        jMenuBar1.add(menuPilas);

        menuArboles.setText("Árboles");
        jMenuBar1.add(menuArboles);

        jMenu1.setText("Colas");

        Ejercicio7.setText("Ejercicio7");
        Ejercicio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio7ActionPerformed(evt);
            }
        });
        jMenu1.add(Ejercicio7);

        Ejercicio8.setText("Ejercicio8");
        jMenu1.add(Ejercicio8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ficha Vehicular");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menuFicha.setText("FichaVehicular");
        menuFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFichaActionPerformed(evt);
            }
        });
        jMenu2.add(menuFicha);

        ReportePagarT.setText("ReportePagarT");
        ReportePagarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportePagarTActionPerformed(evt);
            }
        });
        jMenu2.add(ReportePagarT);

        jMenuBar1.add(jMenu2);

        Gestion.setText("Gestion");
        Gestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionActionPerformed(evt);
            }
        });

        GestionUsuario.setText("GestionUsuario");
        GestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionUsuarioActionPerformed(evt);
            }
        });
        Gestion.add(GestionUsuario);

        jMenuBar1.add(Gestion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opLEstaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLEstaticoActionPerformed
        // TODO add your handling code here:
        //ListasEstaticas ventanaLE=new ListasEstaticas();
        //escritorio.add(ventanaLE);
        //ventanaLE.show();
    }//GEN-LAST:event_opLEstaticoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        FichaVehicular f  = new FichaVehicular();
        escritorio.add(f);
        f.show();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menuFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFichaActionPerformed
        FichaVehicular f  = new FichaVehicular();
        escritorio.add(f);
        f.show();
    }//GEN-LAST:event_menuFichaActionPerformed

    private void OpListasEstaticas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpListasEstaticas2ActionPerformed
 
    }//GEN-LAST:event_OpListasEstaticas2ActionPerformed

    private void ReportePagarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportePagarTActionPerformed
       ReportePagarT f = new ReportePagarT();
       escritorio.add(f);
       f.show();
        
    }//GEN-LAST:event_ReportePagarTActionPerformed

    private void Ejercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio1ActionPerformed
        Ejercicio1 f = new Ejercicio1();
        escritorio.add(f);
        f.show();
    }//GEN-LAST:event_Ejercicio1ActionPerformed

    private void Ejercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio2ActionPerformed
       Ejercicio2 f = new Ejercicio2();
       escritorio.add(f);
       f.show();
    }//GEN-LAST:event_Ejercicio2ActionPerformed

    private void Ejercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio3ActionPerformed
        Ejercicio3 f = new Ejercicio3();
        escritorio.add(f);
        f.show();
    }//GEN-LAST:event_Ejercicio3ActionPerformed

    private void Ejercicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio4ActionPerformed
        Ejercicio4 f = new Ejercicio4();
        escritorio.add(f);
        f.show();
    }//GEN-LAST:event_Ejercicio4ActionPerformed

    private void Ejercicio5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio5ActionPerformed
        Ejercicio5 f = new Ejercicio5();
        escritorio.add(f);
        f.show();
    }//GEN-LAST:event_Ejercicio5ActionPerformed

    private void Ejercicio6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio6ActionPerformed
        Ejercicio6 f = new Ejercicio6();
        escritorio.add(f);
        f.show();
    }//GEN-LAST:event_Ejercicio6ActionPerformed

    private void Ejercicio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio7ActionPerformed
        Ejercicio7 f = new Ejercicio7();
        escritorio.add(f);
        f.show();
    }//GEN-LAST:event_Ejercicio7ActionPerformed

    private void GestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionActionPerformed
          
    }//GEN-LAST:event_GestionActionPerformed

    private void GestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionUsuarioActionPerformed
        personaView f = new personaView();
        escritorio.add(f);
        f.show();
    }//GEN-LAST:event_GestionUsuarioActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ejercicio1;
    private javax.swing.JMenuItem Ejercicio2;
    private javax.swing.JMenuItem Ejercicio3;
    private javax.swing.JMenuItem Ejercicio4;
    private javax.swing.JMenuItem Ejercicio5;
    private javax.swing.JMenuItem Ejercicio6;
    private javax.swing.JMenuItem Ejercicio7;
    private javax.swing.JMenuItem Ejercicio8;
    private javax.swing.JMenu Gestion;
    private javax.swing.JMenuItem GestionUsuario;
    private javax.swing.JMenuItem OpListasEstaticas2;
    private javax.swing.JMenuItem ReportePagarT;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuArboles;
    private javax.swing.JMenuItem menuFicha;
    private javax.swing.JMenu menuPilas;
    private javax.swing.JMenuItem opLDinamicas;
    private javax.swing.JMenu opLEstaticas;
    private javax.swing.JMenuItem opLEstatico;
    // End of variables declaration//GEN-END:variables
}
