/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DIU;

import DIU.vista.ListasDinámicasTabla;

/**
 *
 * @author Usuario
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuListas = new javax.swing.JMenu();
        opLEstatico1 = new javax.swing.JMenuItem();
        opLEstatico2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opLDinamicasPractica = new javax.swing.JMenuItem();
        opDtable = new javax.swing.JMenuItem();
        opLDinamicas3 = new javax.swing.JMenuItem();
        opLDinamicas4 = new javax.swing.JMenuItem();
        menuArboles = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        oplColas7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuPilas = new javax.swing.JMenu();
        oplPila5 = new javax.swing.JMenuItem();
        oplPila6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1387, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        menuListas.setText("Listas Estaticas");

        opLEstatico1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        opLEstatico1.setText("Estáticas 1");
        opLEstatico1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLEstatico1ActionPerformed(evt);
            }
        });
        menuListas.add(opLEstatico1);

        opLEstatico2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        opLEstatico2.setText("Estaticas 2");
        opLEstatico2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLEstatico2ActionPerformed(evt);
            }
        });
        menuListas.add(opLEstatico2);

        jMenuBar1.add(menuListas);

        jMenu3.setText("Listas Dinámicas");

        opLDinamicasPractica.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        opLDinamicasPractica.setText("Practica Listas");
        opLDinamicasPractica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLDinamicasPracticaActionPerformed(evt);
            }
        });
        jMenu3.add(opLDinamicasPractica);

        opDtable.setText("Listas/Table");
        opDtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opDtableActionPerformed(evt);
            }
        });
        jMenu3.add(opDtable);

        opLDinamicas3.setText("Listas Dinámicas 3");
        opLDinamicas3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLDinamicas3ActionPerformed(evt);
            }
        });
        jMenu3.add(opLDinamicas3);

        opLDinamicas4.setText("Listas Dinámicas 4");
        opLDinamicas4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLDinamicas4ActionPerformed(evt);
            }
        });
        jMenu3.add(opLDinamicas4);

        jMenuBar1.add(jMenu3);

        menuArboles.setText("Árboles");
        jMenuBar1.add(menuArboles);

        jMenu1.setText("Colas");

        oplColas7.setText("Colas7");
        oplColas7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oplColas7ActionPerformed(evt);
            }
        });
        jMenu1.add(oplColas7);

        jMenuItem2.setText("Colas 8");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ficha Vehicular");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ver Ficha");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        menuPilas.setText("Pilas");

        oplPila5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        oplPila5.setText("Pilas 5");
        oplPila5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oplPila5ActionPerformed(evt);
            }
        });
        menuPilas.add(oplPila5);

        oplPila6.setText("Pilas 6");
        oplPila6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oplPila6ActionPerformed(evt);
            }
        });
        menuPilas.add(oplPila6);

        jMenuBar1.add(menuPilas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opLEstatico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLEstatico1ActionPerformed
        // TODO add your handling code here:
        ListasEstaticas1 ventanaLE1 = new ListasEstaticas1();
        escritorio.add(ventanaLE1);
        ventanaLE1.show();
    }//GEN-LAST:event_opLEstatico1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        FichaVehicular ventana = new FichaVehicular();
        escritorio.add(ventana);
        ventana.show();
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FichaVehicular ventana = new FichaVehicular();
        escritorio.add(ventana);
        ventana.show();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void oplPila5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oplPila5ActionPerformed
        // TODO add your handling code here:
        Pilas5 ejercicio5 = new Pilas5();
        escritorio.add(ejercicio5);
        ejercicio5.show();
    }//GEN-LAST:event_oplPila5ActionPerformed

    private void opLEstatico2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLEstatico2ActionPerformed
        // TODO add your handling code here:
        ListasEstaticas2 ventanaLE2 = new ListasEstaticas2();
        escritorio.add(ventanaLE2);
        ventanaLE2.show();
    }//GEN-LAST:event_opLEstatico2ActionPerformed

    private void opLDinamicasPracticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLDinamicasPracticaActionPerformed
        // TODO add your handling code here:
        PracticaListasDinamicas ventanaLD = new PracticaListasDinamicas();
        escritorio.add(ventanaLD);
        ventanaLD.show();
    }//GEN-LAST:event_opLDinamicasPracticaActionPerformed

    private void opDtableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opDtableActionPerformed
        // TODO add your handling code here:
        ListasDinámicasTabla ldTable = new ListasDinámicasTabla();
        escritorio.add(ldTable);
        ldTable.show();
    }//GEN-LAST:event_opDtableActionPerformed

    private void opLDinamicas3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLDinamicas3ActionPerformed
        // TODO add your handling code here:
        ListasDinamicas3 ejercicio3 = new ListasDinamicas3();
        escritorio.add(ejercicio3);
        ejercicio3.show();
    }//GEN-LAST:event_opLDinamicas3ActionPerformed

    private void oplPila6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oplPila6ActionPerformed
        // TODO add your handling code here:
        Pilas6 ejercicio6 = new Pilas6();
        escritorio.add(ejercicio6);
        ejercicio6.show();
    }//GEN-LAST:event_oplPila6ActionPerformed

    private void oplColas7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oplColas7ActionPerformed
        // TODO add your handling code here:
        Colas7 ejercicio7 = new Colas7();
        escritorio.add(ejercicio7);
        ejercicio7.show();
    }//GEN-LAST:event_oplColas7ActionPerformed

    private void opLDinamicas4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLDinamicas4ActionPerformed
        // TODO add your handling code here:
        FormularioFutbol ejercicio4 = new FormularioFutbol();
        escritorio.add(ejercicio4);
        ejercicio4.show();
    }//GEN-LAST:event_opLDinamicas4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        SistemaAtencionClientes ejercicio8 = new SistemaAtencionClientes();
        escritorio.add(ejercicio8);
        ejercicio8.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void ejecutarReporte() {
        ReporteValorPagar reporte = new ReporteValorPagar();
        escritorio.add(reporte);
        reporte.show();
    }
    
    public void ejecutarJugadores() {
        FiltrarJugadores jugador = new FiltrarJugadores();
        escritorio.add(jugador);
        jugador.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuArboles;
    private javax.swing.JMenu menuListas;
    private javax.swing.JMenu menuPilas;
    private javax.swing.JMenuItem opDtable;
    private javax.swing.JMenuItem opLDinamicas3;
    private javax.swing.JMenuItem opLDinamicas4;
    private javax.swing.JMenuItem opLDinamicasPractica;
    private javax.swing.JMenuItem opLEstatico1;
    private javax.swing.JMenuItem opLEstatico2;
    private javax.swing.JMenuItem oplColas7;
    private javax.swing.JMenuItem oplPila5;
    private javax.swing.JMenuItem oplPila6;
    // End of variables declaration//GEN-END:variables
}
