/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DIU.modelo.PersonaReport;

/**
 *
 * @author oli
 */
public class Reporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        setModelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValorContaminación = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblValorMatricula = new javax.swing.JLabel();
        lblValorMultas = new javax.swing.JLabel();
        lblValorTipo = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersona = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCarro = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Reporte del vehículo");

        jLabel8.setText("Valor por Matricula:");

        jLabel11.setText("Valor por Multas:");

        jLabel13.setText("Valor por Contaminación:");

        jLabel14.setText("Valor por tipo de vehículo:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Precio total de Matriculación:");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPersona);

        tblCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblCarro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValorContaminación, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValorMultas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(lblValorMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(lblValorMultas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(lblValorContaminación, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(lblValorTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private PersonaReport person1;
    private Carro car1;
    DefaultTableModel modeloPersona=new DefaultTableModel();
    DefaultTableModel modeloCarro=new DefaultTableModel();

    public void transicionPersona(PersonaReport per) {
        this.person1 = per;
    }
    
    public void transicionCarro(Carro car){
        this.car1=car;
    }

    public void setModelo(){
        String[] cabeceraPersona={"Cédula","Nombre"};
        String[] cabeceraCarro={"Marca","Año","Placa","Tipo","Color","Multas","Valor"};
        modeloPersona.setColumnIdentifiers(cabeceraPersona);
        modeloCarro.setColumnIdentifiers(cabeceraCarro);
        tblPersona.setModel(modeloPersona);
    }
    
    public void setFila(){
        Object[] informacionPersona=new Object[modeloPersona.getColumnCount()];
        Object[] informacionCarro=new Object[modeloCarro.getColumnCount()];
        modeloPersona.setRowCount(0);
        modeloCarro.setRowCount(0);
        informacionPersona[0]=person1.getCédula();
        informacionPersona[1]=person1.getNombre();
        informacionCarro[0]=car1.getMarca();
        informacionCarro[1]=car1.getAnioFab();
        informacionCarro[2]=car1.getPlaca();
        informacionCarro[3]=car1.getTipo();
        informacionCarro[4]=car1.getColor();
        informacionCarro[5]=car1.getMulta();
        informacionCarro[6]=car1.getValor();
        modeloPersona.addRow(informacionPersona);
        modeloCarro.addRow(informacionCarro);
        tblPersona.setModel(modeloPersona);
        tblCarro.setModel(modeloCarro);
    }
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        setFila();
        double matriculaTotal = 0.00;
        int anioInt = Integer.parseInt(car1.getAnioFab());
        double valorVehiculo = Double.parseDouble(car1.getValor());
        double marcaTipoValor = 0;
        int sueldoBasico = 435;
        double inicialesValor = 0.00;
        double multasValor = 0.00;
        double cantidadMultaContaminacion = 0;

        if (person1.getCédula().charAt(0) == '1' && car1.getPlaca().charAt(0) == 'I' || car1.getPlaca().charAt(0) == 'i') {
            inicialesValor = sueldoBasico * 0.05;
            matriculaTotal = inicialesValor;
        }
        if (car1.getMulta().equalsIgnoreCase("si")) {
            multasValor = sueldoBasico * 0.25;
            matriculaTotal = matriculaTotal + multasValor;
        }
        if (anioInt < 2010) {
            int diferenciaAnios = 2010 - anioInt;
            double porcentajeAnio = diferenciaAnios * 0.02;
            cantidadMultaContaminacion = 435 * porcentajeAnio;
            matriculaTotal = matriculaTotal + cantidadMultaContaminacion;
        }
        if (car1.getMarca().equalsIgnoreCase("Toyota")) {
            if (car1.getTipo().equalsIgnoreCase("Jeep")) {
                marcaTipoValor = valorVehiculo * 0.08;
            } else if (car1.getTipo().equalsIgnoreCase("Camioneta")) {
                marcaTipoValor = valorVehiculo * 0.12;
            }
        } else if (car1.getMarca().equalsIgnoreCase("Suzuki")) {
            if (car1.getTipo().equalsIgnoreCase("Vitara")) {
                marcaTipoValor = valorVehiculo * 0.1;
            } else if (car1.getTipo().equalsIgnoreCase("automovil")) {
                marcaTipoValor = valorVehiculo * 0.09;
            }
        }
        matriculaTotal = matriculaTotal + marcaTipoValor;

        lblValorMatricula.setText(inicialesValor + "");
        lblValorMultas.setText(multasValor + "");
        lblValorContaminación.setText(cantidadMultaContaminacion + "");
        lblValorTipo.setText(marcaTipoValor + "");
        lblValorTotal.setText(matriculaTotal + "");

    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblValorContaminación;
    private javax.swing.JLabel lblValorMatricula;
    private javax.swing.JLabel lblValorMultas;
    private javax.swing.JLabel lblValorTipo;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JTable tblCarro;
    private javax.swing.JTable tblPersona;
    // End of variables declaration//GEN-END:variables
}
