/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU;

import DIU.Modelo.Jugador;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin
 */
public class TablaJugador extends javax.swing.JInternalFrame {

    public String apellido, edad, puesto, subpuesto, nacionalida, goles;

    public ArrayList<Jugador> jg = new ArrayList<>();

    DefaultTableModel modelo = new DefaultTableModel();
    DefaultTableModel modelos = new DefaultTableModel();

    public void setModelo() {

        String cabecera[] = {"Nro", "Apellido", "Edad", "Puesto", "Subpuesto", "Nacionalidad", "Goles"};
        modelo.setColumnIdentifiers(cabecera);
        tbJugadorJu.setModel(modelo);

    }

    public void setModeloS() {

        String cabecera[] = {"Nro", "Apellido", "Edad", "Puesto", "Subpuesto", "Nacionalidad", "Goles"};
        modelos.setColumnIdentifiers(cabecera);
        tbSenior.setModel(modelos);

    }

    public void agregarDatos() {
        Jugador j = new Jugador(apellido, Integer.parseInt(edad), puesto, subpuesto, nacionalida, Integer.parseInt(goles));
        jg.add(j);

    }

    public void setDatosJunior() {
        modelo.setRowCount(0);
        int n = 1;
        int maxGoles = -1;
        String goleador;
        Object[] datos = new Object[modelo.getColumnCount()];
        for (Jugador jugador : jg) {

            if (jugador.getEdad() < 23) {
                datos[0] = n;
                datos[1] = jugador.getApellidos();
                datos[2] = jugador.getEdad();
                datos[3] = jugador.getPuesto();
                datos[4] = jugador.getSubPuesto();
                datos[5] = jugador.getNacionalidad();
                datos[6] = jugador.getGoles();

                n++;
                modelo.addRow(datos);
                if (jugador.getGoles() > maxGoles) {
                    maxGoles = jugador.getGoles();
                    goleador = jugador.getApellidos();
                    jblGoleadorJ.setText(goleador + " Anotando " + maxGoles);
                }
            }
        }
        tbJugadorJu.setModel(modelo);
    }

    public void setDatosSenior() {
        modelos.setRowCount(0);
        int n = 1;
        int maxGoles = -1;
        String goleador;
        Object[] datos = new Object[modelo.getColumnCount()];
        for (Jugador jugador : jg) {
            
            if (jugador.getEdad() >= 23) {
                datos[0] = n;
                datos[1] = jugador.getApellidos();
                datos[2] = jugador.getEdad();
                datos[3] = jugador.getPuesto();
                datos[4] = jugador.getSubPuesto();
                datos[5] = jugador.getNacionalidad();
                datos[6] = jugador.getGoles();

                n++;
                modelos.addRow(datos);
                if (jugador.getGoles() > maxGoles) {
                maxGoles = jugador.getGoles();
                goleador = jugador.getApellidos();
                jblGoleadorS.setText(goleador + " Anotando " + maxGoles);
            }
            }
        }
        tbSenior.setModel(modelos);
    }

    public TablaJugador() {
        initComponents();
        setModelo();
        setModeloS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbJugadorJu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSenior = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jblGoleadorS = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jblGoleadorJ = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tabla de los Jugadores");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tbJugadorJu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbJugadorJu);

        jLabel1.setText("Junior");

        jLabel2.setText("Senior");

        tbSenior.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbSenior);

        jLabel3.setText("El goleador de la categoria Senior es:");

        jLabel4.setText("El goleador de la categoria Junior es:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jblGoleadorJ, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addComponent(jblGoleadorS, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(277, 277, 277))))
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jblGoleadorJ, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jblGoleadorS, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        this.agregarDatos();
        this.setDatosJunior();
        this.setDatosSenior();

    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jblGoleadorJ;
    private javax.swing.JLabel jblGoleadorS;
    private javax.swing.JTable tbJugadorJu;
    private javax.swing.JTable tbSenior;
    // End of variables declaration//GEN-END:variables
}
