/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kevin
 */
public class TablaDinamico extends javax.swing.JInternalFrame {

    DefaultTableModel dtm = new DefaultTableModel();
    ArrayList<Integer> numeros1 = new ArrayList<>();

    int suma, cantidad;
    double promedio;

    /**
     * Creates new form TablaDinamico
     */
    public TablaDinamico() {
        initComponents();
        this.numeros1 = new ArrayList<>();
        this.columnas();

    }

    public void columnas() {
        String[] columna = new String[numeros1.size() + 3];
        for (int i = 0; i < columna.length; i++) {
            columna[i] = "Numero " + (i + 1);
        }
        columna[numeros1.size()] = "Suma";
        columna[numeros1.size() + 1] = "Promedio";
        columna[numeros1.size() + 2] = "Mayores al Promedio";
        dtm.setColumnIdentifiers(columna);
        jTable1.setModel(dtm);
    }

    public void agregarNumeros() {
        int tamanio = numeros1.size();
        Object[] obj = new Object[tamanio + 3];

        for (int i = 0; i < tamanio; i++) {
            obj[i] = numeros1.get(i);
        }

        obj[tamanio] = suma;
        obj[tamanio + 1] = promedio;
        obj[tamanio + 2] = cantidad;

        dtm.addRow(obj);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Tabla Numeros");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(517, 517, 517)
                .addComponent(jLabel1)
                .addContainerGap(511, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
