package DIU.Tareas;

import java.util.Stack;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Belial
 */
public class Ejercicio6 extends javax.swing.JInternalFrame {

    private Stack<Integer> torre1, torre2, torre3;
    private DefaultTableModel tblTorre1, tblTorre2, tblTorre3;
    private int contador;

    /**
     * Creates new form Ejercicio6
     */
    public Ejercicio6() {
        initComponents();
        iniciarPila();
        actualizarTablas();
    }

    private void iniciarPila() {
        torre1 = new Stack<>();
        torre2 = new Stack<>();
        torre3 = new Stack<>();
        tblTorre1 = (DefaultTableModel) jTorre1.getModel();
        tblTorre2 = (DefaultTableModel) JTorre2.getModel();
        tblTorre3 = (DefaultTableModel) JTorre3.getModel();
        contador = 0;

        torre1.push(3);
        torre1.push(2);
        torre1.push(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTorre2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTorre1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTorre3 = new javax.swing.JTable();
        btnRestablecer = new javax.swing.JButton();
        btnResolver = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("EJERCICIO 6: PILAS");
        setToolTipText("");

        JTorre2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTorre2);

        jTorre1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre 1"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTorre1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTorre1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(jTorre1);

        JTorre3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Torre 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(JTorre3);

        btnRestablecer.setText("Restablecer");
        btnRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestablecerActionPerformed(evt);
            }
        });

        btnResolver.setText("Resolver");
        btnResolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnResolver, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(btnRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRestablecer)
                    .addComponent(btnResolver))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTorre1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTorre1AncestorAdded

    }//GEN-LAST:event_jTorre1AncestorAdded

    private void btnRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestablecerActionPerformed
        iniciarPila();
        contador = 0;
        actualizarTablas();
    }//GEN-LAST:event_btnRestablecerActionPerformed

    private void btnResolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResolverActionPerformed
        resolver();
        actualizarTablas();

    }//GEN-LAST:event_btnResolverActionPerformed
    private void resolver() {
        switch (contador) {
            case 0:
                moverDisco(torre1, torre3); // Paso 1: Mover disco 1 de A a C
                break;
            case 1:
                moverDisco(torre1, torre2); // Paso 2: Mover disco 2 de A a B
                break;
            case 2:
                moverDisco(torre3, torre2); // Paso 3: Mover disco 1 de C a B
                break;
            case 3:
                moverDisco(torre1, torre3); // Paso 4: Mover disco 3 de A a C
                break;
            case 4:
                moverDisco(torre2, torre1); // Paso 5: Mover disco 1 de B a A
                break;
            case 5:
                moverDisco(torre2, torre3); // Paso 6: Mover disco 2 de B a C
                break;
            case 6:
                moverDisco(torre1, torre3); // Paso 7: Mover disco 1 de A a C
                break;
            default:
                contador = -1;
                break;
        }

        contador++;
        actualizarTablas();
    }

    private void moverDisco(Stack<Integer> origen, Stack<Integer> destino) {
        if (!origen.isEmpty()) {
            int disco = origen.pop();
            destino.push(disco);
        }
    }

    private void actualizarTablas() {
        actualizarTabla(tblTorre1, torre1);
        actualizarTabla(tblTorre2, torre2);
        actualizarTabla(tblTorre3, torre3);
    }

    private void actualizarTabla(DefaultTableModel model, Stack<Integer> torre) {
        model.setRowCount(0);
        for (int i = torre.size() - 1; i >= 0; i--) {
            model.addRow(new Object[]{torre.get(i)});
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTorre2;
    private javax.swing.JTable JTorre3;
    private javax.swing.JButton btnResolver;
    private javax.swing.JButton btnRestablecer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTorre1;
    // End of variables declaration//GEN-END:variables
}
