/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Pilas;

import java.util.Stack;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sarita
 */
public class Ejercicio_6 extends javax.swing.JInternalFrame {
    DefaultTableModel modelo1, modelo2, modelo3;
    Stack<Integer> torre1, torre2, torre3;
    /**
     * Creates new form Ejercicio_6
     */
    public Ejercicio_6() {
        initComponents();
       this.inicializarTorres();
    }
    
    private void inicializarTorres() {
       
       // Inicializar las pilas
    torre1 = new Stack<>();
    torre2 = new Stack<>();
    torre3 = new Stack<>();

    
    modelo1 = new DefaultTableModel(new Object[][]{}, new String[]{"TORRE 1"});
    modelo2 = new DefaultTableModel(new Object[][]{}, new String[]{"TORRE 2"});
    modelo3 = new DefaultTableModel(new Object[][]{}, new String[]{"TORRE 3"});

    
    tb1.setModel(modelo1);
    tb2.setModel(modelo2);
    tb3.setModel(modelo3);
    }

    private void iniciarJuego() {
        // Limpia las pilas y las tablas
        torre1.clear();
        torre2.clear();
        torre3.clear();
        limpiarTablas();

        // Inicializa las pilas con los discos
        int numDiscos = 3;
        for (int i = numDiscos; i >= 1; i--) {
            torre1.push(i);
        }

        
        this.imprimirTorres();
    }

    private void limpiarTablas() {
        modelo1.setRowCount(0);
        modelo2.setRowCount(0);
        modelo3.setRowCount(0);
    }

    private void imprimirTorres() {
        
        for (int disco : torre1) {
            modelo1.addRow(new Object[]{disco});
        }

        
        for (int disco : torre2) {
            modelo2.addRow(new Object[]{disco});
        }

        
        for (int disco : torre3) {
            modelo3.addRow(new Object[]{disco});
        }
    }

    private int cont = 0; 
    private void moverDisco() {
        cont++;

         switch (cont) {
        case 1:
            torre3.push(torre1.pop());
            break;
        case 2:
            torre2.push(torre1.pop());
            break;
        case 3:
            torre2.push(torre3.pop());
            break;
        case 4:
            torre3.push(torre1.pop());
            break;
        case 5:
            torre1.push(torre2.pop());
            break;
        case 6:
            torre3.push(torre2.pop());
            break;
        case 7:
            torre3.push(torre1.pop());
            lblMensaje.setText("FIN DEL JUEGO");
            break;
        default:
            break;
        }
 
        limpiarTablas();
        imprimirTorres();
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        btnIniciar = new javax.swing.JButton();
        btnMover = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("EJERCICIO 6_ TORRES DE HANOI _ PILAS");

        jLabel1.setText("EJERCICIO 6");

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb1);

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tb2);

        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tb3);

        btnIniciar.setText("INICIAR_JUEGO");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        btnMover.setText("CAMBIAR");
        btnMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoverActionPerformed(evt);
            }
        });

        lblMensaje.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(198, 198, 198)
                        .addComponent(btnMover))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnIniciar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar)
                    .addComponent(lblMensaje))
                .addGap(250, 250, 250))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        this.iniciarJuego();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoverActionPerformed
        // TODO add your handling code here:
        this.moverDisco();
    }//GEN-LAST:event_btnMoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnMover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTable tb3;
    // End of variables declaration//GEN-END:variables
}
