/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU.Vista;

import java.util.LinkedList;
import java.util.Queue;
import javax.swing.JTextArea;

/**
 *
 * @author jefe
 */
public class Ejercicio7 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ejercicio7
     */
    public Ejercicio7() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblIngreseCola1 = new javax.swing.JLabel();
        lblCola2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCola3 = new javax.swing.JTextArea();
        txtCola1 = new javax.swing.JTextField();
        txtCola2 = new javax.swing.JTextField();
        bttnConfirmar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblTitulo.setText("Ejercicio7");

        lblIngreseCola1.setText("Ingrese la primera cola");

        lblCola2.setText("Ingresar la segunda cola");

        txtAreaCola3.setColumns(20);
        txtAreaCola3.setRows(5);
        jScrollPane1.setViewportView(txtAreaCola3);

        bttnConfirmar.setText("Confirmar");
        bttnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngreseCola1)
                            .addComponent(lblCola2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCola2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(txtCola1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttnConfirmar)
                            .addComponent(lblTitulo))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitulo)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIngreseCola1)
                    .addComponent(txtCola1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCola2)
                    .addComponent(txtCola2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(bttnConfirmar)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConfirmarActionPerformed
        // TODO add your handling code here:
       String cola1Texto = txtCola1.getText();
    String cola2Texto = txtCola2.getText();

    // Convertir los textos a colas de enteros
    Queue<Integer> cola1 = convertirTextoACola(cola1Texto);
    Queue<Integer> cola2 = convertirTextoACola(cola2Texto);

    // Sumar las colas y obtener la cola resultado
    Queue<Integer> resultado = sumarColas(cola1, cola2);

    // Mostrar la cola resultado en el txtAreaCola3
    mostrarColaEnTextArea(resultado, txtAreaCola3);      
    }//GEN-LAST:event_bttnConfirmarActionPerformed

    private Queue<Integer> convertirTextoACola(String texto) {
    Queue<Integer> cola = new LinkedList<>();
    String[] numeros = texto.split(",");
    for (String numero : numeros) {
        cola.add(Integer.parseInt(numero.trim()));
    }
    return cola;
}

    private Queue<Integer> sumarColas(Queue<Integer> cola1, Queue<Integer> cola2) {
    Queue<Integer> resultado = new LinkedList<>();

    // Verificar que ambas colas tengan la misma longitud
    if (cola1.size() != cola2.size()) {
        // Puedes manejar este caso según tus necesidades
        System.out.println("Las colas no tienen la misma longitud");
        return resultado;
    }

    // Sumar elementos uno a uno y agregar el resultado a la nueva cola
    while (!cola1.isEmpty() && !cola2.isEmpty()) {
        int suma = cola1.poll() + cola2.poll();
        resultado.add(suma);
    }

    return resultado;
}
    
private void mostrarColaEnTextArea(Queue<Integer> cola, JTextArea textArea) {
    textArea.setText(""); // Limpiar el JTextArea antes de mostrar la nueva cola
    for (Integer elemento : cola) {
        textArea.append(elemento + "\n");
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnConfirmar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCola2;
    private javax.swing.JLabel lblIngreseCola1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtAreaCola3;
    private javax.swing.JTextField txtCola1;
    private javax.swing.JTextField txtCola2;
    // End of variables declaration//GEN-END:variables
}
