/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU.Vista;

import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import DIU.Modelo.Jugador;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jefe
 */
public class Ejercicio4 extends javax.swing.JInternalFrame {
        private ArrayList<Jugador> jugadores = new ArrayList<>();
    private DefaultTableModel tablaModelo;

    /**
     * Creates new form Ejercicio4
     */
    public Ejercicio4() {
        initComponents();
  tablaModelo = new DefaultTableModel();
        jTable1.setModel(tablaModelo);
        // Añadir las columnas a la tabla
        tablaModelo.addColumn("Apellidos");
        tablaModelo.addColumn("Edad");
        tablaModelo.addColumn("Puesto");
        tablaModelo.addColumn("Habilidad");
        tablaModelo.addColumn("Nacionalidad");
        tablaModelo.addColumn("Goles");
    }
    
    public String[] datos(String datos){
    String[]informacion=new String[4];
 
    if(datos.equalsIgnoreCase("Portero")){
    informacion[0]="Portero"; 
}   
 if(datos.equalsIgnoreCase("Defensa")){
    informacion[0]="Defensa central";
    informacion[1]="Lateral";
    informacion[2]="Libre";
    informacion[3]="Carrilero" ; 
 }
 if(datos.equalsIgnoreCase("Centro campista")){
    informacion[0]="Pivote";
    informacion[1]="Media punta";
    informacion[2]="Volante";
    informacion[3]="Interior" ; 
 }
   if(datos.equalsIgnoreCase("Delantero")){
    informacion[0]="Segundo Delantero";
    informacion[1]="Delantero centro";
    informacion[2]="extremmo";
    
 }
return informacion;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblapellidos = new javax.swing.JLabel();
        lbledad = new javax.swing.JLabel();
        lblnacionalidad = new javax.swing.JLabel();
        lblgoles = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtGoles = new javax.swing.JTextField();
        ComboboxPuesto = new javax.swing.JComboBox<>();
        lblpuesto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ComboboxPosicion = new javax.swing.JComboBox<>();
        bttnestadisticas = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("EJERCICIO4");

        lblapellidos.setText("APELLIDOS");

        lbledad.setText("EDAD");

        lblnacionalidad.setText("NACIONALIDAD");

        lblgoles.setText("GOLES");

        ComboboxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Portero", "Defensa", "Centro campista", "Delantero" }));
        ComboboxPuesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboboxPuestoItemStateChanged(evt);
            }
        });
        ComboboxPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboboxPuestoActionPerformed(evt);
            }
        });

        lblpuesto.setText("Puesto");

        jButton1.setText("Mostrar Jugador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        bttnestadisticas.setText("Estadisticas");
        bttnestadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnestadisticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblnacionalidad))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblpuesto)
                                            .addComponent(lbledad)
                                            .addComponent(lblapellidos)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lblgoles)))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ComboboxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(ComboboxPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(txtGoles, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnestadisticas)
                        .addGap(62, 62, 62)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblapellidos)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbledad)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ComboboxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ComboboxPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblpuesto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnacionalidad)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblgoles)
                            .addComponent(txtGoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(bttnestadisticas))
                        .addGap(56, 56, 56))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
      
    private void ComboboxPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboboxPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboboxPuestoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String apellidos = txtApellidos.getText();
        int edad = Integer.parseInt(txtEdad.getText());
        String nacionalidad = txtNacionalidad.getText();
        int goles = Integer.parseInt(txtGoles.getText());

        String puesto = ComboboxPuesto.getSelectedItem().toString();
        String habilidad = ComboboxPosicion.getSelectedItem().toString();

        Jugador jugador = new Jugador(apellidos, edad, puesto, habilidad, nacionalidad, goles);
        jugadores.add(jugador);

        mostrarJugadoresEnTabla();
    
    }//GEN-LAST:event_jButton1ActionPerformed
private void mostrarJugadoresEnTabla() {
       tablaModelo.setRowCount(0);

        // Llenar la tabla con los datos de los jugadores
        for (Jugador jugador : jugadores) {
            Object[] fila = {
                jugador.getApellidos(),
                jugador.getEdad(),
                jugador.getPuesto(),
                jugador.getHabilidad(),
                jugador.getNacionalidad(),
                jugador.getGoles()
            };
            tablaModelo.addRow(fila);
        }
    }

    private void filtrarJugadores(int edadLimite, String categoria) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Jugador jugador : jugadores) {
            if (("Juvenil".equals(categoria) && jugador.getEdad() < edadLimite) ||
                ("Senior".equals(categoria) && jugador.getEdad() >= edadLimite)) {
                model.addRow(new Object[]{jugador.getApellidos(), jugador.getEdad(), jugador.getNacionalidad(), jugador.getGoles()});
            }
        }
    }
    
    private void ComboboxPuestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboboxPuestoItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
        if(this.ComboboxPuesto.getSelectedIndex()>0){
        this.ComboboxPosicion.setModel(new DefaultComboBoxModel(this.datos(this.ComboboxPuesto.getSelectedItem().toString())));
        }
        }
    }//GEN-LAST:event_ComboboxPuestoItemStateChanged

    private void bttnestadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnestadisticasActionPerformed
        // TODO add your handling code here:
                mostrarInformacionAdicional();
    }//GEN-LAST:event_bttnestadisticasActionPerformed


    private void mostrarInformacionAdicional() {
        int totalJugadoresJuveniles = 0;
        int totalJugadoresSenior = 0;
        Jugador maximoGoleadorJuvenil = null;
        Jugador maximoGoleadorSenior = null;

        for (Jugador jugador : jugadores) {
            if (jugador.getEdad() < 23) {
                totalJugadoresJuveniles++;
                if (maximoGoleadorJuvenil == null || jugador.getGoles() > maximoGoleadorJuvenil.getGoles()) {
                    maximoGoleadorJuvenil = jugador;
                }
            } else {
                totalJugadoresSenior++;
                if (maximoGoleadorSenior == null || jugador.getGoles() > maximoGoleadorSenior.getGoles()) {
                    maximoGoleadorSenior = jugador;
                }
            }
        }

        String mensaje = "Total de jugadores juveniles: " + totalJugadoresJuveniles + "\n";
        mensaje += "Total de jugadores senior: " + totalJugadoresSenior + "\n";

        if (maximoGoleadorJuvenil != null) {
            mensaje += "Goleador juvenil: " + maximoGoleadorJuvenil.getApellidos() + " con " + maximoGoleadorJuvenil.getGoles() + " goles\n";
        }

        if (maximoGoleadorSenior != null) {
            mensaje += "Goleador senior: " + maximoGoleadorSenior.getApellidos() + " con " + maximoGoleadorSenior.getGoles() + " goles\n";
        }

        JOptionPane.showMessageDialog(this, mensaje, "Información Adicional", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboboxPosicion;
    private javax.swing.JComboBox<String> ComboboxPuesto;
    private javax.swing.JButton bttnestadisticas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblapellidos;
    private javax.swing.JLabel lbledad;
    private javax.swing.JLabel lblgoles;
    private javax.swing.JLabel lblnacionalidad;
    private javax.swing.JLabel lblpuesto;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtGoles;
    private javax.swing.JTextField txtNacionalidad;
    // End of variables declaration//GEN-END:variables
}
