/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andy Moya
 */
public class ListaPalabras extends javax.swing.JInternalFrame {
     Map<String, Integer> frecuenciaPalabras = new HashMap<>(); 
     List<String> listaPalabras = new ArrayList<>();
     DefaultTableModel modelo = new DefaultTableModel();
     
    /**
     * Creates new form ListaPalabras
     */
    public ListaPalabras() {
        initComponents();
        modelo.addColumn("Palabras");
    }
    void buscar(String pala){   
    for (String palabra : listaPalabras) {
            int frecuenciaActual = frecuenciaPalabras.getOrDefault(palabra, 0);
            frecuenciaPalabras.put(palabra, frecuenciaActual + 1);
        }
    int frecuencia = frecuenciaPalabras.getOrDefault(pala, 0);
        JOptionPane.showMessageDialog(rootPane, "La palabra '" + pala
                + "' aparece " + frecuencia + " veces en la lista.");
    System.out.println("La palabra '" + pala + "' aparece " + frecuencia + " veces en la lista.");
    frecuenciaPalabras.put(pala, 0);
    }
    void mostrar(){
//    for (String dato : listaPalabras) {
//            modelo.addRow(new Object[]{dato});
//        }
     // Eliminar todas las filas actuales
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        for (String fila : listaPalabras) {
            modelo.addRow(new Object[]{fila});
        }

    tbl_palabras.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_palabra = new javax.swing.JTextField();
        btm_ingreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_palabras = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_busqueda = new javax.swing.JTextField();
        btm_busqueda = new javax.swing.JButton();
        btn_mostrar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("DICCIONARIO");

        jLabel2.setText("PALABRA:");

        btm_ingreso.setText("ingresar");
        btm_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_ingresoActionPerformed(evt);
            }
        });

        tbl_palabras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_palabras);

        jLabel3.setText("BUSCAR:");

        btm_busqueda.setText("buscar");
        btm_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm_busquedaActionPerformed(evt);
            }
        });

        btn_mostrar.setText("mostrar lista");
        btn_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_palabra, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(txt_busqueda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btm_ingreso)
                    .addComponent(btm_busqueda))
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(175, 175, 175))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btn_mostrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_ingreso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btm_busqueda))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_mostrar)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_ingresoActionPerformed
    String palabra = txt_palabra.getText();
    listaPalabras.add(palabra); 
    }//GEN-LAST:event_btm_ingresoActionPerformed

    private void btm_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm_busquedaActionPerformed
    
    String pala = txt_busqueda.getText();
    buscar(pala);
     
    }//GEN-LAST:event_btm_busquedaActionPerformed

    private void btn_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarActionPerformed
        mostrar();
    }//GEN-LAST:event_btn_mostrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm_busqueda;
    private javax.swing.JButton btm_ingreso;
    private javax.swing.JButton btn_mostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_palabras;
    private javax.swing.JTextField txt_busqueda;
    private javax.swing.JTextField txt_palabra;
    // End of variables declaration//GEN-END:variables
}
