package DIU.EjerciciosFichaVehicular;

import DIU.CONTROLADOR.VehiculoControlador;
import static DIU.EjerciciosFichaVehicular.FichaVehicular.txtCedula;
import DIU.modelo.Persona;
import DIU.modelo.Vehiculo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Belial
 */
public class TablaVehiculo extends javax.swing.JInternalFrame {

    public String nombre, cedula, placa, marca, color, valor, multas, tipo, añoFabricacion;
    ArrayList<Vehiculo> listaVehiculosLD = new ArrayList<>();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form TablaVehiculo
     */
    public TablaVehiculo() {
        initComponents();
        setModelo();
    }

     public void setModelo() {
        String[] cabecera = {"Cédula", "Nombres", "Placa", "Color", "Marca", "Tipo", "Valor"};
        modelo.setColumnIdentifiers(cabecera);
        tblDatosVehiculares.setModel(modelo);
    }


    public void llenarTabla() {
        // Limpiar la tabla antes de llenarla
        modelo.setRowCount(0);

        // Obtener los vehículos de la base de datos
        Persona persona = new Persona();
        VehiculoControlador controlador = new VehiculoControlador();
        ArrayList<Object[]> vehiculos = controlador.obtenerVehiculosPorPersona(persona);


        // Llenar la tabla con los datos de los vehículos obtenidos
        if (vehiculos != null) {
            for (Object[] fila : vehiculos) {
                modelo.addRow(fila);
            }
        }
    }

//    public void setDatos() {
//        Object[] filas = new Object[modelo.getColumnCount()];
//        int cont = 1;
//        for (Vehiculo puntero : listaVehiculosLD) {
//            filas[0] = cont;
//            filas[1] = puntero.getPlaca();
//            filas[2] = puntero.getMarca();
//            filas[3] = puntero.getTipo();
//            filas[4] = puntero.getAñoFabricacion();
//            filas[5] = puntero.getColor();
//            filas[6] = puntero.getValor();
//            filas[7] = puntero.getMultas();
//            modelo.addRow(filas);
//            cont++;
//        }
//        tblDatosVehiculares.setModel(modelo);
////        lblNombre.setText(nombre);
////        lblCedula.setText(cedula);
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatosVehiculares = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblDatosVehiculares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatosVehiculares);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("LOS DATOS DE SUS VEHÍCULOS SON:");

        jButton1.setText("ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Cedula:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formInternalFrameActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         int cedula = Integer.parseInt(txtCedula.getText());
    Persona persona = new Persona();
    persona.setCedula(cedula); // Suponiendo que tienes un método setCedula en tu clase Persona
    
    // Llamar al método obtenerVehiculosPorPersona del controlador
    ArrayList<Object[]> vehiculos = controlador.obtenerVehiculosPorPersona(persona);
    
    // Luego, puedes usar los datos obtenidos en vehiculos para mostrarlos en la tabla
    // Por ejemplo, podrías actualizar la tabla con estos datos
    // Supongamos que tu tabla se llama tblDatosVehiculares
    DefaultTableModel modeloTabla = (DefaultTableModel) tblDatosVehiculares.getModel();
    modeloTabla.setRowCount(0); // Limpiar la tabla antes de agregar nuevos datos
    
    // Luego, agregar los datos de vehiculos a la tabla
    for (Object[] fila : vehiculos) {
        modeloTabla.addRow(fila);
    }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDatosVehiculares;
    private javax.swing.JTextField txtCedula;
    // End of variables declaration//GEN-END:variables
}
