/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package DIU.vistas;

import DIU.Moldelos.Persona;
import DIU.Moldelos.Vehiculo;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER-HP
 */
public class TablaFichaVehicular extends javax.swing.JInternalFrame {
    
    DefaultTableModel dfm = new DefaultTableModel();
    ArrayList<Vehiculo> listaNombres = new ArrayList();
    ArrayList<Vehiculo> listaVehiculo = new ArrayList();

    /**
     * new Creates new form TablaFichaVehicular
     */
    public TablaFichaVehicular() {
        initComponents();
        setModelo();
    }

    public void setModelo() {
        String[] cabecera = {"Nro", "Placa", "Marca", "Tipo", "fecha", "color", "valor"};
        dfm.setColumnIdentifiers(cabecera);
        tblVehiculo.setModel(dfm);
    }

    public void llenarVehiculo() {
        Vehiculo v = new Vehiculo(title, title, title, title, title, title);
       listaVehiculo.add(v);
        
        Persona p = new Persona(title, WIDTH, listaNombres);
         listaNombres.add(v);
    }
    public void setDatos(){
        Object [] filas = new Object[dfm.getColumnCount()];
        int cont=1;
        for (Vehiculo puntero : listaVehiculo) {
            filas[0]=cont;
            filas[1]=1;
            filas[2]=2;
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVehiculo = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("TABLA FICHA VEHICULAR");

        tblVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblVehiculo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVehiculo;
    // End of variables declaration//GEN-END:variables
}
