package Arrayslist;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class EJEM_4 extends javax.swing.JInternalFrame {

    /**
     * Creates new form EJEM_4
     */
    public EJEM_4() {
        initComponents();
    }
    public String[] subpuestos(String puesto) {
    String[] subpuestos = new String[4];
   if (puesto.equalsIgnoreCase("Portero")) {
            subpuestos[0] = "Portero";
        }
        if (puesto.equalsIgnoreCase("Defensa")) {
            subpuestos[0] = "Defensa central";
            subpuestos[1] = "Defensa Lateral";
            subpuestos[2] = "Defensa Libre";
            subpuestos[3] = "Defensa:Carrilero";
        }

        if (puesto.equalsIgnoreCase("Centrocampista")) {
            subpuestos[0] = "Cen Pivote";
            subpuestos[1] = "Cen Media punta";
            subpuestos[2] = "Cen Volante";
            subpuestos[3] = "Cen Interior";
        }

        if (puesto.equalsIgnoreCase("Delantero")) {
            subpuestos[0] = "Segundo delantero";
            subpuestos[1] = "Delantero centro";
            subpuestos[2] = "Delan Extremo";
        }
        return subpuestos;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        boxpuesto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boxcentro = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbjugadores = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtnacionalidad = new javax.swing.JTextField();
        txtgoles = new javax.swing.JTextField();
        txtsenior = new javax.swing.JTextField();
        txtjuvenil = new javax.swing.JTextField();
        btngoleadores = new javax.swing.JButton();
        btniniciar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("JUGADORES");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Apellidos :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel3.setText("Edad :");

        boxpuesto.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        boxpuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Portero", "Defensa", "Centrocampista", "Delantero" }));
        boxpuesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxpuestoItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("selecione :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("seleccione :");

        boxcentro.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel7.setText("Goles :");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Nacionalidad :");

        tbjugadores.setBackground(new java.awt.Color(204, 255, 204));
        tbjugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "APELLIDOS", "EDAD", "JUGADOR", "PUESTO", "NACIONALIDAD", "GOLES"
            }
        ));
        jScrollPane1.setViewportView(tbjugadores);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel9.setText("Goleador juvenil :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel10.setText("Goleador senior :");

        txtapellido.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        txtedad.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        txtnacionalidad.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        txtgoles.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N

        txtsenior.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtsenior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseniorActionPerformed(evt);
            }
        });

        txtjuvenil.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtjuvenil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjuvenilActionPerformed(evt);
            }
        });

        btngoleadores.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btngoleadores.setText("VER GOLEADORES");
        btngoleadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngoleadoresActionPerformed(evt);
            }
        });

        btniniciar.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btniniciar.setText("AGREGAR");
        btniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(boxcentro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(boxpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(109, 109, 109)
                                        .addComponent(btniniciar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(btngoleadores))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtsenior, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtjuvenil, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)))
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtgoles, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btngoleadores)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtsenior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtjuvenil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxpuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(btniniciar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxcentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtgoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtseniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseniorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseniorActionPerformed

    private void txtjuvenilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjuvenilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjuvenilActionPerformed
    ArrayList<Jugador> jugadores = new ArrayList<>();
    private void btniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciarActionPerformed
           
        String apellidos = txtapellido.getText();
        int edad = Integer.parseInt(txtedad.getText());
        String puesto = boxcentro.getSelectedItem().toString();
        String nacionalidad = txtnacionalidad.getText();
        int goles = Integer.parseInt(txtgoles.getText());

        Jugador jugador = new Jugador(apellidos, edad, puesto, nacionalidad, goles);
        jugadores.add(jugador);
        actualizarTabla();
        limpiarCampos();
    }//GEN-LAST:event_btniniciarActionPerformed

    private void btngoleadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngoleadoresActionPerformed
        // TODO add your handling code here:
            int goleadorjuvenil = 0;
    int goleadorsenior = 0;
    String goleadorJuvenil = "";
    String goleadorSenior = "";

    for (Jugador jugador : jugadores) {
        if (jugador.getEdad() > 23) { // Jugador senior
            if (jugador.getGoles() > goleadorsenior) {
                goleadorsenior = jugador.getGoles();
                goleadorSenior = jugador.getApellidos();
            }
        } else { // Jugador juvenil
            if (jugador.getGoles() > goleadorjuvenil) {
                goleadorjuvenil = jugador.getGoles();
                goleadorJuvenil = jugador.getApellidos();
            }
        }
    }

    txtsenior.setText(goleadorSenior);
    txtjuvenil.setText(goleadorJuvenil);

    // Agrega la siguiente línea para actualizar la tabla después de calcular los goleadores
    actualizarTabla();
    }//GEN-LAST:event_btngoleadoresActionPerformed

    private void boxpuestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxpuestoItemStateChanged
         if (evt.getStateChange() == ItemEvent.SELECTED) {
        if (this.boxpuesto.getSelectedIndex() > 0) {
            this.boxcentro.setModel(new DefaultComboBoxModel(this.subpuestos(this.boxpuesto.getSelectedItem().toString())));
        }
         }
    }//GEN-LAST:event_boxpuestoItemStateChanged


private void actualizarTabla() {
    DefaultTableModel modeloTabla = (DefaultTableModel) tbjugadores.getModel();
    modeloTabla.setRowCount(0);

    for (Jugador jugador : jugadores) {
        String tipoJugador;
        if (jugador.getEdad() > 23) {
            tipoJugador = "Senior";
        } else {
            tipoJugador = "Juvenil";
        }
        modeloTabla.addRow(new Object[]{
            jugador.getApellidos(),
            jugador.getEdad(), tipoJugador, jugador.getPuesto(), jugador.getNacionalidad(),
            jugador.getGoles(),
        });
    }
}


private void limpiarCampos() {
    txtapellido.setText("");
    txtedad.setText("");
    txtnacionalidad.setText("");
    txtgoles.setText("");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxcentro;
    private javax.swing.JComboBox<String> boxpuesto;
    private javax.swing.JButton btngoleadores;
    private javax.swing.JButton btniniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbjugadores;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtgoles;
    private javax.swing.JTextField txtjuvenil;
    private javax.swing.JTextField txtnacionalidad;
    private javax.swing.JTextField txtsenior;
    // End of variables declaration//GEN-END:variables
}
